# Generated by Django 5.2 on 2025-06-25 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0007_delete_paiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Client Stripe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Client Stripe',
                'verbose_name_plural': 'Clients Stripe',
            },
        ),
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True, verbose_name='ID Payment Intent Stripe')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='eur', max_length=3, verbose_name='Devise')),
                ('statut', models.CharField(choices=[('requires_payment_method', 'En attente de méthode de paiement'), ('requires_confirmation', 'En attente de confirmation'), ('requires_action', 'Action requise par le client'), ('processing', 'En cours de traitement'), ('succeeded', 'Réussi'), ('canceled', 'Annulé'), ('failed', 'Échoué')], default='requires_payment_method', max_length=30, verbose_name='Statut du Paiement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_paiement_reussi', models.DateTimeField(blank=True, null=True, verbose_name='Date du paiement réussi')),
                ('commande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_payment', to='transport.commande', verbose_name='Commande Associée')),
                ('stripe_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='a_stripe.stripecustomer', verbose_name='Client Stripe')),
            ],
            options={
                'verbose_name': 'Paiement Stripe',
                'verbose_name_plural': 'Paiements Stripe',
                'ordering': ['-date_creation'],
            },
        ),
    ]
