# Generated by Django 5.1.8 on 2025-06-03 00:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur Associé')),
                ('numero_permis', models.CharField(max_length=50, unique=True, verbose_name='Numéro de Permis')),
                ('date_expiration_permis', models.DateField(blank=True, null=True, verbose_name="Date d'Expiration du Permis")),
                ('disponibilite_statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_mission', 'En Mission'), ('en_repos', 'En Repos')], default='disponible', max_length=20, verbose_name='Statut de Disponibilité')),
                ('notes_chauffeur_profil', models.TextField(blank=True, null=True, verbose_name='Notes sur le Chauffeur')),
            ],
            options={
                'verbose_name': 'Chauffeur',
                'verbose_name_plural': 'Chauffeurs',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur Associé')),
                ('adresse_facturation', models.TextField(blank=True, null=True, verbose_name='Adresse de Facturation')),
                ('preferences_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Préférences de Contact')),
                ('notes_client', models.TextField(blank=True, null=True, verbose_name='Notes sur le Client')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='GestionnaireLogistique',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur Associé')),
                ('matricule_employe', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matricule Employé')),
                ('telephone_professionnel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone Professionnel')),
            ],
            options={
                'verbose_name': 'Gestionnaire Logistique',
                'verbose_name_plural': 'Gestionnaires Logistiques',
            },
        ),
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_etapes_json', models.JSONField(blank=True, null=True, verbose_name='Points Étapes (JSON)')),
                ('distance_totale_km_estimee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distance Estimée (km)')),
                ('duree_totale_estimee_heures', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Durée Estimée (heures)')),
            ],
            options={
                'verbose_name': 'Itinéraire',
                'verbose_name_plural': 'Itinéraires',
            },
        ),
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200, unique=True, verbose_name="Nom de l'Entreprise")),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contact')),
                ('contact_telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone de Contact')),
                ('details_contrat', models.TextField(blank=True, null=True, verbose_name='Détails du Contrat')),
            ],
            options={
                'verbose_name': 'Transporteur',
                'verbose_name_plural': 'Transporteurs',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_commande', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence Commande')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('description_marchandise', models.TextField(verbose_name='Description Marchandise')),
                ('poids_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Poids (kg)')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volume (m³)')),
                ('adresse_chargement', models.TextField(verbose_name='Adresse de Chargement')),
                ('adresse_livraison', models.TextField(verbose_name='Adresse de Livraison')),
                ('date_souhaitee_livraison', models.DateField(verbose_name='Date Souhaitée de Livraison')),
                ('statut_commande', models.CharField(choices=[('en_attente_validation', 'En attente de validation'), ('validee', 'Validée'), ('planifiee', 'Planifiée'), ('paiement_en_attente', 'Paiement en attente'), ('en_cours_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente_validation', max_length=30, verbose_name='Statut de la Commande')),
                ('instructions_speciales', models.TextField(blank=True, null=True, verbose_name='Instructions Spéciales')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='transport.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planification_debut', models.DateTimeField(verbose_name='Date Planification Début')),
                ('date_planification_fin_estimee', models.DateTimeField(blank=True, null=True, verbose_name='Date Planification Fin Estimée')),
                ('statut_livraison', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours_chargement', 'En cours de chargement'), ('en_transit', 'En transit'), ('livree_partiellement', 'Livrée partiellement'), ('livree_totalement', 'Livrée totalement'), ('probleme_signale', 'Problème signalé'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='planifiee', max_length=30, verbose_name='Statut de la Livraison')),
                ('notes_internes_livraison', models.TextField(blank=True, null=True, verbose_name='Notes Internes')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livraisons', to='transport.chauffeur', verbose_name='Chauffeur')),
                ('commandes', models.ManyToManyField(related_name='livraisons_associees', to='transport.commande', verbose_name='Commandes Associées')),
                ('itineraire', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.itineraire', verbose_name='Itinéraire')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('methode_paiement', models.CharField(choices=[('carte_bancaire', 'Carte Bancaire'), ('virement', 'Virement'), ('espece_a_livraison', 'Espèce à la livraison')], max_length=30, verbose_name='Méthode de Paiement')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du Paiement')),
                ('statut_paiement', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20, verbose_name='Statut du Paiement')),
                ('reference_transaction_externe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence Transaction Externe')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='transport.commande', verbose_name='Commande Associée')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_evenement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horodatage Événement')),
                ('statut_reporte', models.CharField(max_length=100, verbose_name='Statut Reporté')),
                ('photo_preuve_url', models.URLField(blank=True, null=True, verbose_name='URL Photo Preuve')),
                ('signature_recepteur_url', models.URLField(blank=True, null=True, verbose_name='URL Signature Récepteur')),
                ('notes_evenement', models.TextField(blank=True, null=True, verbose_name="Notes sur l'Événement")),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_suivi', to='transport.livraison', verbose_name='Livraison Associée')),
            ],
            options={
                'verbose_name': 'Événement de Suivi',
                'verbose_name_plural': 'Événements de Suivi',
                'ordering': ['-timestamp_evenement'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True, verbose_name='Immatriculation')),
                ('type_vehicule', models.CharField(max_length=100, verbose_name='Type de Véhicule')),
                ('capacite_poids_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacité Poids (kg)')),
                ('capacite_volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacité Volume (m³)')),
                ('statut_vehicule', models.CharField(choices=[('disponible', 'Disponible'), ('en_mission', 'En Mission'), ('en_maintenance', 'En Maintenance')], default='disponible', max_length=20, verbose_name='Statut du Véhicule')),
                ('localisation_actuelle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localisation Actuelle')),
                ('consommation_moyenne_l_100km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Consommation (L/100km)')),
                ('transporteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='transport.transporteur', verbose_name='Transporteur Propriétaire')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
            },
        ),
        migrations.AddField(
            model_name='livraison',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livraisons', to='transport.vehicule', verbose_name='Véhicule'),
        ),
    ]
