# Generated by Django 5.1.8 on 2025-06-20 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraire',
            name='duree_totale_estimee_heures',
        ),
        migrations.RemoveField(
            model_name='itineraire',
            name='points_etapes_json',
        ),
        migrations.AddField(
            model_name='itineraire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 20, 0, 5, 36, 646195, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itineraire',
            name='duree_totale_sec_estimee',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée Estimée (secondes)'),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='geometry_geojson',
            field=models.JSONField(blank=True, null=True, verbose_name='Géométrie Tracé (GeoJSON)'),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='instructions_textuelles',
            field=models.TextField(blank=True, null=True, verbose_name='Instructions Textuelles'),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='points_etapes_str',
            field=models.TextField(blank=True, null=True, verbose_name='Points Étapes (Texte/Original)'),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='raw_ors_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Réponse Brute ORS'),
        ),
    ]
