# Generated by Django 5.1.8 on 2025-06-20 02:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_remove_itineraire_duree_totale_estimee_heures_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transporteur',
            options={},
        ),
        migrations.AddField(
            model_name='transporteur',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'Inscription"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transporteur',
            name='nom',
            field=models.CharField(default='', max_length=100, verbose_name='Nom du Responsable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transporteur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur Associé'),
        ),
    ]
