# Generated by Django 5.1.8 on 2025-06-22 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_vehicule_created_at_vehicule_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itineraire',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Itinéraire', 'verbose_name_plural': 'Itinéraires'},
        ),
        migrations.AlterModelOptions(
            name='livraison',
            options={'ordering': ['-date_planification_debut'], 'verbose_name': 'Livraison', 'verbose_name_plural': 'Livraisons'},
        ),
        migrations.AlterModelOptions(
            name='transporteur',
            options={'verbose_name': 'Transporteur (Partenaire)', 'verbose_name_plural': 'Transporteurs (Partenaires)'},
        ),
        migrations.AlterModelOptions(
            name='vehicule',
            options={'ordering': ['immatriculation'], 'verbose_name': 'Véhicule', 'verbose_name_plural': 'Véhicules'},
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='reference_transaction_externe',
        ),
        migrations.AddField(
            model_name='commande',
            name='motif_annulation',
            field=models.TextField(blank=True, null=True, verbose_name="Motif d'Annulation/Refus"),
        ),
        migrations.AddField(
            model_name='livraison',
            name='date_effective_debut',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Effective Début'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='date_effective_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Effective Fin'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference_transaction_passerelle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transaction Passerelle'),
        ),
        migrations.AddField(
            model_name='suivi',
            name='localisation_texte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Localisation (Texte)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de Création'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='commandes',
            field=models.ManyToManyField(related_name='livraisons', to='transport.commande', verbose_name='Commandes Associées'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut_livraison',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('en_attente_chargement', 'En attente de chargement'), ('en_cours_chargement', 'En cours de chargement'), ('en_transit', 'En transit'), ('arrivee_destination', 'Arrivée à destination'), ('terminee', 'Terminée (Livrée)'), ('probleme_signale', 'Problème signalé'), ('annulee', 'Annulée')], default='planifiee', max_length=30, verbose_name='Statut de la Livraison'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='commande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='transport.commande', verbose_name='Commande Associée'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du Paiement Effectif'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode_paiement',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=30, verbose_name='Méthode de Paiement (Passerelle)'),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contact (Affichage)'),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'Enregistrement"),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom du Responsable/Contact'),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Compte Utilisateur Associé'),
        ),
    ]
