# Generated by Django 5.1.8 on 2025-06-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_itineraire_options_alter_livraison_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='duree_estimee_heures',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5, verbose_name='Durée estimée (heures)'),
        ),
    ]
