# Generated by Django 5.2 on 2025-06-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_livraison_duree_estimee_heures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
