# Generated by Django 5.2 on 2025-06-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_commande_montant_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut_commande',
            field=models.CharField(choices=[('en_attente_validation', 'En attente de validation'), ('paiement_en_attente', 'En attente de paiement'), ('validee', 'Payée (Validée)'), ('planifiee', 'Planifiée'), ('en_cours_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente_validation', max_length=30, verbose_name='Statut de la Commande'),
        ),
    ]
