# Generated by Django 5.1.8 on 2025-06-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_alter_commande_statut_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils_clients/'),
        ),
    ]
