# Generated by Django 5.1.8 on 2025-07-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_client_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils_transporteurs/', verbose_name='Photo de profil'),
        ),
    ]
